### ISSUE TITLE
Some plugin ids are not generated

### ISSUE THREAD

**Issue by jmfayard** [jmfayard/refreshVersions#106] opened 2019-10-13 18:42 UTC
Check why the Kotlin and Android plugin Ids are not generated here

https://github.com/LouisCAD/Splitties/pull/215/commits/6332f5f6675c83c7e07656dcfa4c3a56f5d9fcae

**Comment by sierisimo** [comment] 2019-10-14 06:19
Can you elaborate in the explanation? I'm not totally following the commit message/information  or how we can fix this. 

I landed here from your posts about gradle on Dev.to + an error happening for the `detekt` plugin in the [Dev.to Android App](https://github.com/thepracticaldev/DEV-Android/). I would like to help on fixing this issue (if possible as I see the issue is reported on Jetbrains and Google) or knowing a workaround for it (currently removing `detekt` from plugins block and adding manually `id("…detekt")` makes me feel like cheating.

**Comment by jmfayard** [comment] 2019-10-14 06:30
Hello @sierisimo 
Currently the plugins detection is not very sophisticated. 
The `:dependencyUpdates` task produce a json with dependencies, some of which end up with `.gradle.plugin`
https://github.com/jmfayard/buildSrcVersions/blob/master/sample-versionsOnlyMode/report.json#L16-L21

I don't know yet how to make it better, but I think that would require having a look at the Gradle `buildScript` configurations..

**Closed** 2020-10-18 05:32 UTC
Labels: bug, help wanted
