### ISSUE TITLE
How to migrate an existing project to refreshVersions

### ISSUE THREAD

**Issue by jmfayard** [jmfayard/refreshVersions#268] opened 2020-10-15 15:15 UTC
- *Status:*  I wrote the documentation of the migration process as I imagine it. 
- Implementation: I have a draft implementation of `./gradlew refreshVersions --show missing-versions` in the branch [poc-all-versions](https://github.com/jmfayard/refreshVersions/tree/poc-all-versions)

---

# refreshVersions migration

As described in [Adding Dependencies](https://jmfayard.github.io/refreshVersions/adding-dependencies/), refreshVersions has an opt-in mechanism. It only manages dependencies that were declared with a version placeholder `_`

```kotlin
dependencies {
   implementation("com.squareup.okhttp3:okhttp:_") // OK, managed
   implementation("com.squareup.moshi:moshi:1.9.3") // Harcoded, not managed
}
```

## The chicken and egg problem

If you migrate an existing project, all dependencies versions will be hardcoded, so refreshVersions will manage nothing

```kotlin
## versions.properties

# no version whatsoever here :'(
```

So how do you migrate?

You could replace directly all hardcoded versions with the placeholder

```diff
// build.gradle
dependencies {
   implementation("com.squareup.okhttp3:okhttp:_")
-   implementation("com.squareup.moshi:moshi:1.9.3")
+   implementation("com.squareup.moshi:moshi:_")
}
```

Sync Gradle.

You will then notice an unwanted side-effect:

```diff
## versions.properties
+version.moshi=1.11.0
```

That's not good, moshi was silently updated to the latest available version instead of the one that the build was using 🤨

So here is what you do instead

## Add missing versions

Run the following command

```bash
$ ./gradlew refreshVersions --show missing-versions
> Task refreshVersions
Following versions are currently missing in versions.properties:

version.okhttp=4.8.3
version.moshi=1.11.0
```

Use the output of this command to modify manually `versions.properties`

```diff
## versions.properties
+version.okhttp=4.8.3
+version.moshi=1.11.0
```

## Replace hardcoded dependencies versions

The next step is to find and replace all hardcoded versions with the placeholder `_`.

Depending on the size of the project, this could be simple or a bit tricky. 

Fortunately, we have another command that will guide you in this process

```bash
$ ./gradlew refreshVersions --show harcoded-versions
> Task refreshVersions
Searching for hardcoded versions...

# core/build.gradle
Found 1 hardcoded dependency:
moshi

# app/build.gradle.kts
Found 3 harcoded dependencies:
cardview constraintlayout picaso
```

Search those dependencies and replace the hardcoded version with `_`

```diff
// core/build.gradle
-   implementation 'com.squareup.moshi:moshi:1.9.3'
+   implementation 'com.squareup.moshi:moshi:_'

// app/build.gradle.kts
-   implementation("com.squareup.moshi:moshi:1.9.3")
-   implementation("androidx.constraintlayout:constraintlayout:1.2.0")
-   implementation("com.squareup.picasso:picaso:1.0.0")
+   implementation("com.squareup.moshi:moshi:_")
+   implementation("androidx.constraintlayout:constraintlayout:_")
+   implementation("com.squareup.picasso:picaso:_")
```

Check again that you have no hard-coded version

```bash
$ ./gradlew refreshVersions --show harcoded-versions
> Task refreshVersions
Searching for hardcoded versions...

# core/build.gradle
No harcoded version

# app/build.gradle.kts
No harcoded version
```

Commit your changes

## Run `$ ./gradlew refreshVersions`

At that point, your project is setup correctly. You have the same versions as before but can now lookup for available updates

```properties
$ ./gradlew refreshVersions
$ cat versions.properties
## versions.properties

version.okhttp=4.8.3
## # available=4.9.0

version.moshi=1.11.0
## #available=1.13.0 
```

**Comment by jmfayard** [comment] 2020-10-16 12:07
@LouisCAD ^ above is the doc of the migration process that I plan to implement.
Feel free to comment, especially about use cases, naming, ...

**Comment by LouisCAD** [comment] 2020-10-16 13:23
We can do better (though we have great ideas and a clear explanation of the problem).

Please let me comment more in depth this weekend. I'll prioritize this over reviewing the website updates.

**Comment by LouisCAD** [comment] 2020-10-18 01:27
First of all, I'm reminding you that I started an MVP (minimum viable product) Gradle task to assist migration.
It's UX is far from perfect, there are known issues, but it gets the job done safely if you ignore the problems.

All it's waiting for is getting improved.

I'm putting the permalink of the old documentation that mentions it, and I'm going to mention it on the website as well, along with a few words on its experimental status and the fact that there are know UX issues. (Which were already present in the old doc that has been broken a little too early).

https://github.com/jmfayard/refreshVersions/blob/c40b68672f376bf8a0e3c0f9fd6e5271c10db4ca/docs/Setting-up.adoc#step-2-migrating-the-dependencies-versions-declaration-place

So there's no chicken and egg problem, just improvements to do (which might include full-rewrite if better or needed).

Improving the UX of this task has always been in my plans for 1.0, I just didn't have the time yet.

Now, I think its name is too long. Using a flag for `refreshVersions` named `--migrate` or alike would certainly be simpler (the `--console=plain` would still be required).

## What can be improved in the existing migration task
1. Ergonomics (Don't require to type a full word to validate migration of a single dependency)
2. Keep track of what has been migrated already to not show outdated hardcoded dependencies count
3. Automatically replace dependency notations in the build files when possible safely
4. Have better rules to ignore dependencies added by plugins (e.g. "kotlin-android-extensions" plugin)
5. Its name (remove lengthy `migrateToRefreshVersionsDependenciesConstants ` and have a `--migrate` flag to `refreshVersions` redirect to it instead)

**Comment by LouisCAD** [comment] 2020-10-18 01:55
Closing this issue, because it's actually a duplicate of #169 that I added to my priority list (but we can discuss handing that to you @jmfayard if you want).

**Closed by LouisCAD** 2020-10-18 01:55 UTC

**Comment by THEAccess** [comment] 2021-04-03 22:43
From my experience the best migration can be done with Regex and Find&Replace. `\${Versions\.[A-Za-z]*}` worked well
